import { useEffect, useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

import axios from '/utils/rest';

import { SimpleGrid, Text, Container, Space, Card, Group, Badge, Button, useMantineTheme, Loader } from '@mantine/core';

export default function Home() {
	const [coursesLoading, setCoursesLoading] = useState(false);
	const [coursesError, setCoursesError] = useState(false);
	const [courses, setCourses] = useState([]);

	const theme = useMantineTheme();

	const secondaryColor = theme.colorScheme === 'dark'
		? theme.colors.dark[1]
		: theme.colors.gray[7];

	useEffect(() => {
		setCoursesLoading(true);
		axios.get('/main/courses')
			.then(res => {
				if (res.status === 200) {
					setCourses(res.data);
				} else {
					setCoursesError('Ошибка получения списка курсов, пожалуйста, попробуйте позже');
				}
			})
			.catch(error => {
				console.log(error);
				setCoursesError('Ошибка получения списка курсов, пожалуйста, попробуйте позже');
			})
			.finally(() => {
				setCoursesLoading(false);
			})
	}, [])

	return (
		<div className={styles.container}>
			<Head>
				<title>Инкубатор талантов</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container>
				<Space h="xl" />
				<Text size="xl" weight={700} color="orange" transform="uppercase">
					Доступные курсы
				</Text>
				<Text color="red" weight={500}>
					{coursesError}
				</Text>
				<Space h="lg" />
				{coursesLoading && <Loader color="orange" variant="bars" />}
				<SimpleGrid cols={3}>
					{!coursesLoading && courses.map(course => {
						return <Card p="lg" key={course.id} style={{ boxShadow: '0 0 12px #999', marginBottom: '20px' }}>
							<Card.Section>
								<Image src={'/' + course.image} width={300} height={180} alt="Инкубатор талантов" />
							</Card.Section>

							<Group position="apart" style={{ marginBottom: 5, marginTop: theme.spacing.sm }}>
								<Text weight={500}>{course.name}</Text>
							</Group>
							<Link passHref href={`/courses/${course.id}`}>
								<Button color="green" fullWidth style={{ marginTop: 14 }}>
									Начать обучение
								</Button>
							</Link>
						</Card>
					})}
				</SimpleGrid>
			</Container>
		</div>
	)
}
