import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

import {Center} from '@mantine/core';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Инкубатор талантов</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Center>Привет</Center>
		</div>
	)
}
