import { useEffect, useState } from 'react';
import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import axios from '/utils/rest';

import { SimpleGrid, Text, Container, Space, Card, Group, Badge, Button, useMantineTheme, Loader } from '@mantine/core';

export default function Tasks() {
	const router = useRouter()
	const { id, day_id } = router.query
	const [tasksLoading, setTasksLoading] = useState(false);
	const [dayLoading, setDayLoading] = useState(false);
	const [tasksError, setTasksError] = useState(false);
	const [day, setDay] = useState([]);
	const [course, setCourse] = useState([]);
	const [dayError, setDayError] = useState([]);
	const [tasks, setTasks] = useState([]);

	const theme = useMantineTheme();

	const secondaryColor = theme.colorScheme === 'dark'
		? theme.colors.dark[1]
		: theme.colors.gray[7];

	useEffect(() => {
		if (id && day_id) {
			setTasksLoading(true);
			setDayLoading(true);
			axios.get(`/main/courses/${id}`)
				.then(res => {
					if (res.status === 200) {
						if (res.data.length === 1) {
							setCourse(res.data[0]);
						}
					}
				})
				.catch(error => {
					console.log(error);
				})
			axios.get(`/main/courses/${id}/days/${day_id}`)
				.then(res => {
					if (res.status === 200) {
						setDay(res.data);
					} else {
						setDayError('Ошибка получения курса, пожалуйста, попробуйте позже');
					}
				})
				.catch(error => {
					console.log(error);
					setDayError('Ошибка получения курса, пожалуйста, попробуйте позже');
				})
				.finally(() => {
					setDayLoading(false);
				})
			axios.get(`/main/courses/${id}/days/${day_id}/tasks`)
				.then(res => {
					if (res.status === 200) {
						setTasks(res.data);
					} else {
						setTasksError('Ошибка получения списка заданий, пожалуйста, попробуйте позже');
					}
				})
				.catch(error => {
					console.log(error);
					setTasksError('Ошибка получения списка заданий, пожалуйста, попробуйте позже');
				})
				.finally(() => {
					setTasksLoading(false);
				})
		}
	}, [id, day_id])

	return (
		<>
			<Head>
				<title>Инкубатор талантов</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container>
				<Space h="xl" />
				<Card p="lg">
					{dayLoading && <Loader color="orange" variant="bars" />}
					<Card.Section>
						{day.image ?
							<Image src={'/' + day.image} width={1200} height={550} alt="Инкубатор талантов" /> :
							course.image ? <Image src={'/' + course.image} width={1200} height={550} alt="Инкубатор талантов" /> :
								<></>
						}
					</Card.Section>

					<Group position="apart" style={{ marginBottom: 5, marginTop: theme.spacing.sm }}>
						<Text weight={500}>{day.name}</Text>
					</Group>

					<Text size="sm" weight={500} style={{ color: secondaryColor, lineHeight: 1.5 }}
						dangerouslySetInnerHTML={{ __html: day.description }}>
					</Text>

					<Space h="lg" />
					{tasksLoading && <Loader color="orange" variant="bars" />}
					<Text color="red" weight={500}>
						{tasksError}
					</Text>
					{!tasksLoading && tasks.map(task => {
						return <Card p="lg" key={course.id} style={{ boxShadow: '0 0 12px #999', marginBottom: '20px' }}>
							<Card.Section>
								{task.image && <Image src={'/' + task.image} width={300} height={120} alt="Инкубатор талантов" />}
							</Card.Section>

							<Group position="apart" style={{ marginBottom: 5, marginTop: theme.spacing.sm }}>
								<Text size="lg" weight={700} color="orange">{task.name}</Text>
							</Group>
							<Link passHref href={`/courses/${course.id}/days/${day_id}/tasks/${task.id}`}>
								<Button color="green" fullWidth style={{ marginTop: 14 }}>
									Открыть день
								</Button>
							</Link>
						</Card>
					})}
				</Card>
			</Container>
		</>
	)
}
